### PR TITLE
Improve documentation based on the testing

### PR DESCRIPTION
**Pull request by kant2002**

### CODE REVIEW

**Comment by shushanhf** [comment]
@kant2002 
Thanks very much ~
If you need some help about LoongArch64's environment, please tell me.

**Comment by kant2002** [comment]
@shushanhf my current understanding that I should cross build on Linux using CoreRoot and then transfer files to cloud instance. is this correct? or is there a way to start building on the LA instance fully?

**Comment by shushanhf** [comment]
@shushanhf my current understanding that I should cross build on Linux using CoreRoot and then transfer files to cloud instance. is this correct? 

Yes, becasuse for the runtime8.0 there is no LA-SDK right now.
now we are building a temporary LA-SDK7.0, I will upload it after gerenating it.

> or is there a way to start building on the LA instance fully?

right now there is only the SDK6.0-LA which can build the runtime fully on LA.

**Comment by shushanhf** [comment]
@kant2002 
Can you generate the LA's instructions on x86-linux by AOT mode?

I will also try to build the crossgen2 on LA by the runtime8.0.

**Comment by kant2002** [comment]
For now, I'm trying to simply repeat of the build process which you have. I look at this as an opportunity improve LA documentation process. Is this repo is good place to raise issues about building of LA ?

**Pull request merged**
